ci: update jobs order in destroy pipeline

diff --git a/.github/workflows/tf-plan-destroy-apply.yaml b/.github/workflows/tf-plan-destroy-apply.yaml
--- a/.github/workflows/tf-plan-destroy-apply.yaml
+++ b/.github/workflows/tf-plan-destroy-apply.yaml
@@ -42,7 +42,6 @@ env:
   DEPLOYMENT_PATH: ${{ github.workspace }}/terraform/deployments
   TF_VAR_FILE: ${{ github.workspace }}/terraform/environments/${{ inputs.environment }}.tfvars
   # Terraform Specific Env Variables
-  CURRENT_GIT_TAG: ${{ github.ref_name }}
   DESIRED_COUNT: "${{ vars.DESIRED_COUNT }}"
   IMAGE: camillehe1992/strapi:${{ inputs.image_tag }}
   # Strapi Specific Env Variables
@@ -56,8 +55,8 @@ env:
   DATABASE_PASSWORD: "${{ secrets.DATABASE_PASSWORD }}"
 
 jobs:
-  terraform-plan-shared:
-    name: Terraform Plan Shared
+  terraform-plan-app:
+    name: Terraform Plan App
     runs-on: ubuntu-latest
     environment: ${{ inputs.environment }}
     env:
@@ -85,10 +84,148 @@ jobs:
           aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
 
-      # Checks that all Terraform configuration files adhere to a canonical format
-      # Will fail the build if not
-      - name: Terraform Format
-        run: make lint
+      - name: Terraform Init & Plan Destroy
+        id: tf-plan
+        run: |
+          export exitcode=0
+          make DEPLOYMENT=app plan-destroy
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+
+          if [ $exitcode -eq 1 ]; then
+            echo Terraform Plan Failed!
+            exit 1
+          else 
+            exit 0
+          fi
+
+      # # Terraform Init
+      # - name: Terraform Init
+      #   run: make DEPLOYMENT=app init
+
+      # # Generates an execution plan for Terraform
+      # # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+      # - name: Terraform Init & Plan Destroy
+      #   id: tf-plan
+      #   working-directory: ${{ env.DEPLOYMENT_PATH }}/app
+      #   run: |
+      #     export exitcode=0
+      #     terraform plan -destroy -var-file $TF_VAR_FILE  \
+      #       -var="aws_region=$AWS_REGION" \
+      #       -var="environment=$ENVIRONMENT" \
+      #       -var="nickname=$NICKNAME" \
+      #       -var="state_bucket=$STATE_BUCKET" \
+      #       -var="image=$IMAGE" \
+      #       -var="desired_count=$DESIRED_COUNT" \
+      #       -var="app_keys=$APP_KEYS" \
+      #       -var="api_token_salt=$API_TOKEN_SALT" \
+      #       -var="admin_jwt_secret=$ADMIN_JWT_SECRET" \
+      #       -var="transfer_token_salt=$TRANSFER_TOKEN_SALT" \
+      #       -var="jwt_secret=$JWT_SECRET" \
+      #       -var="database_host=$DATABASE_HOST" \
+      #       -var="database_username=$DATABASE_USERNAME" \
+      #       -var="database_password=$DATABASE_PASSWORD" \
+      #       -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+
+      #     echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+
+      #     if [ $exitcode -eq 1 ]; then
+      #       echo Terraform Plan Failed!
+      #       exit 1
+      #     else
+      #       exit 0
+      #     fi
+
+      # Save plan to artifacts
+      - name: Publish Terraform Plan
+        uses: actions/upload-artifact@v3
+        with:
+          name: tfplan
+          path: ${{ env.DEPLOYMENT_PATH }}/app/tfplan
+
+      # Create string output of Terraform Plan
+      - name: Create String Output
+        id: tf-plan-string
+        working-directory: ${{ env.DEPLOYMENT_PATH }}/app
+        run: |
+          TERRAFORM_PLAN=$(terraform show -no-color tfplan)
+
+          delimiter="$(openssl rand -hex 8)"
+          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
+          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
+          echo "" >> $GITHUB_OUTPUT
+          echo '```terraform' >> $GITHUB_OUTPUT
+          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
+          echo '```' >> $GITHUB_OUTPUT
+          echo "</details>" >> $GITHUB_OUTPUT
+          echo "${delimiter}" >> $GITHUB_OUTPUT
+
+      # Publish Terraform Plan as task summary
+      - name: Publish Terraform Plan to Task Summary
+        env:
+          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
+        run: |
+          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+
+  terraform-apply-app:
+    name: Terraform Apply App
+    if: ${{ inputs.force == true }} || needs.terraform-plan.outputs.tfplanExitCode == 2
+    runs-on: ubuntu-latest
+    environment: ${{ inputs.environment }}
+    needs: [terraform-plan-app]
+
+    steps:
+      # Checkout the repository to the GitHub Actions runner
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_wrapper: false
+          terraform_version: ${{ env.TF_VERSION }}
+
+      # Download saved plan from artifacts
+      - name: Download Terraform Plan
+        uses: actions/download-artifact@v3
+        with:
+          name: tfplan
+          path: ${{ env.DEPLOYMENT_PATH }}/app
+
+      # Terraform Apply
+      - name: Terraform Init & Apply
+        run: make DEPLOYMENT=app apply
+
+  terraform-plan-shared:
+    name: Terraform Plan Shared
+    runs-on: ubuntu-latest
+    environment: ${{ inputs.environment }}
+    needs: [terraform-apply-app]
+    env:
+      #this is needed since we are running terraform with read-only permissions
+      ARM_SKIP_PROVIDER_REGISTRATION: true
+    outputs:
+      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
+
+    steps:
+      # Checkout the repository to the GitHub Actions runner
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      # Install the latest version of the Terraform CLI
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_wrapper: false
+          terraform_version: ${{ env.TF_VERSION }}
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
 
       # Generates an execution plan for Terraform
       # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
@@ -167,132 +304,3 @@ jobs:
       # Terraform Apply
       - name: Terraform Init & Apply
         run: make DEPLOYMENT=shared apply
-
-  terraform-plan-app:
-    name: Terraform Plan App
-    runs-on: ubuntu-latest
-    environment: ${{ inputs.environment }}
-    needs: [terraform-apply-shared]
-    env:
-      #this is needed since we are running terraform with read-only permissions
-      ARM_SKIP_PROVIDER_REGISTRATION: true
-    outputs:
-      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
-
-    steps:
-      # Checkout the repository to the GitHub Actions runner
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      # Install the latest version of the Terraform CLI
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_wrapper: false
-          terraform_version: ${{ env.TF_VERSION }}
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
-
-      # Terraform Init
-      - name: Terraform Init
-        run: make DEPLOYMENT=app init
-
-      # Generates an execution plan for Terraform
-      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
-      - name: Terraform Init & Plan Destroy
-        id: tf-plan
-        working-directory: ${{ env.DEPLOYMENT_PATH }}/app
-        run: |
-          export exitcode=0
-          terraform plan -destroy -var-file $TF_VAR_FILE  \
-            -var="aws_region=$AWS_REGION" \
-            -var="environment=$ENVIRONMENT" \
-            -var="nickname=$NICKNAME" \
-            -var="state_bucket=$STATE_BUCKET" \
-            -var="image=$IMAGE" \
-            -var="desired_count=$DESIRED_COUNT" \
-            -var="app_keys=$APP_KEYS" \
-            -var="api_token_salt=$API_TOKEN_SALT" \
-            -var="admin_jwt_secret=$ADMIN_JWT_SECRET" \
-            -var="transfer_token_salt=$TRANSFER_TOKEN_SALT" \
-            -var="jwt_secret=$JWT_SECRET" \
-            -var="database_host=$DATABASE_HOST" \
-            -var="database_username=$DATABASE_USERNAME" \
-            -var="database_password=$DATABASE_PASSWORD" \
-            -detailed-exitcode -no-color -out tfplan || export exitcode=$?
-
-          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-
-          if [ $exitcode -eq 1 ]; then
-            echo Terraform Plan Failed!
-            exit 1
-          else 
-            exit 0
-          fi
-
-      # Save plan to artifacts
-      - name: Publish Terraform Plan
-        uses: actions/upload-artifact@v3
-        with:
-          name: tfplan
-          path: ${{ env.DEPLOYMENT_PATH }}/app/tfplan
-
-      # Create string output of Terraform Plan
-      - name: Create String Output
-        id: tf-plan-string
-        working-directory: ${{ env.DEPLOYMENT_PATH }}/app
-        run: |
-          TERRAFORM_PLAN=$(terraform show -no-color tfplan)
-
-          delimiter="$(openssl rand -hex 8)"
-          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
-          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
-          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
-          echo "" >> $GITHUB_OUTPUT
-          echo '```terraform' >> $GITHUB_OUTPUT
-          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
-          echo '```' >> $GITHUB_OUTPUT
-          echo "</details>" >> $GITHUB_OUTPUT
-          echo "${delimiter}" >> $GITHUB_OUTPUT
-
-      # Publish Terraform Plan as task summary
-      - name: Publish Terraform Plan to Task Summary
-        env:
-          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
-        run: |
-          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
-
-  terraform-apply-app:
-    name: Terraform Apply App
-    if: ${{ inputs.force == true }} || needs.terraform-plan.outputs.tfplanExitCode == 2
-    runs-on: ubuntu-latest
-    environment: ${{ inputs.environment }}
-    needs: [terraform-plan-app]
-
-    steps:
-      # Checkout the repository to the GitHub Actions runner
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_wrapper: false
-          terraform_version: ${{ env.TF_VERSION }}
-
-      # Download saved plan from artifacts
-      - name: Download Terraform Plan
-        uses: actions/download-artifact@v3
-        with:
-          name: tfplan
-          path: ${{ env.DEPLOYMENT_PATH }}/app
-
-      # Terraform Apply
-      - name: Terraform Init & Apply
-        run: make DEPLOYMENT=app apply
